org.springframework.jdbc.support java.sql.SQLException import org.junit.Test import org.springframework.dao.ConcurrencyFailureException import org.springframework.dao.DataAccessException import org.springframework.dao.DataAccessResourceFailureException import org.springframework.dao.DataIntegrityViolationException import org.springframework.dao.TransientDataAccessResourceException import org.springframework.jdbc.BadSqlGrammarException import org.springframework.jdbc.UncategorizedSQLException import static static org.junit.Assert.* import class org.springframework.jdbc.support.SQLStateSQLExceptionTranslatorTests String String String = public = public throws new public public throws public public throws public public throws public public throws public public throws public public throws SQLExceptionTranslator DataAccessException SQLException private private < decl_stmt java.sql.SQLException = new decl_stmt org.springframework.jdbc.support.SQLExceptionTranslator = new decl_stmt DataAccessException = call SQLExceptionTranslator.translate() call SQLExceptionTranslator.translate() call SQLExceptionTranslator.translate() call SQLExceptionTranslator.translate() call SQLExceptionTranslator.translate() call DataAccessException.getClass() call DataAccessException.getClass() call DataAccessException.getClass() call DataAccessException.getClass() call DataAccessException.getClass() call DataAccessException.getCause() call DataAccessException.getCause() call DataAccessException.getCause() call DataAccessException.getCause() call DataAccessException.getCause() call DataAccessException.getCause() call DataAccessException.getCause() call DataAccessException.getCause() call DataAccessException.getCause() call DataAccessException.getCause()